// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import "context"

const createAlbum = `
INSERT INTO albums (user_id, name, description, cover_asset_id)
VALUES ($1::uuid, $2, $3, $4::uuid)
RETURNING id::text, user_id::text, name, description, cover_asset_id::text, is_archived, created_at, updated_at
`

type CreateAlbumParams struct {
	UserID       string
	Name         string
	Description  *string
	CoverAssetID *string
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	return scanAlbum(q.db.QueryRow(ctx, createAlbum, arg.UserID, arg.Name, arg.Description, arg.CoverAssetID))
}

const listAlbums = `
SELECT id::text, user_id::text, name, description, cover_asset_id::text, is_archived, created_at, updated_at
FROM albums
WHERE user_id = $1::uuid
ORDER BY created_at DESC
`

func (q *Queries) ListAlbums(ctx context.Context, userID string) ([]Album, error) {
	rows, err := q.db.Query(ctx, listAlbums, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	albums := make([]Album, 0)
	for rows.Next() {
		album, err := scanAlbum(rows)
		if err != nil {
			return nil, err
		}
		albums = append(albums, album)
	}
	return albums, rows.Err()
}

const getAlbumByIDForUser = `
SELECT id::text, user_id::text, name, description, cover_asset_id::text, is_archived, created_at, updated_at
FROM albums
WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetAlbumByIDForUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAlbumByIDForUser(ctx context.Context, arg GetAlbumByIDForUserParams) (Album, error) {
	return scanAlbum(q.db.QueryRow(ctx, getAlbumByIDForUser, arg.ID, arg.UserID))
}

const updateAlbum = `
UPDATE albums
SET name = $3, description = $4, cover_asset_id = $5::uuid, is_archived = $6
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text, user_id::text, name, description, cover_asset_id::text, is_archived, created_at, updated_at
`

type UpdateAlbumParams struct {
	ID           string
	UserID       string
	Name         string
	Description  *string
	CoverAssetID *string
	IsArchived   bool
}

func (q *Queries) UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) (Album, error) {
	return scanAlbum(q.db.QueryRow(ctx, updateAlbum, arg.ID, arg.UserID, arg.Name, arg.Description, arg.CoverAssetID, arg.IsArchived))
}

const deleteAlbum = `DELETE FROM albums WHERE id = $1::uuid AND user_id = $2::uuid`

func (q *Queries) DeleteAlbum(ctx context.Context, arg GetAlbumByIDForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAlbum, arg.ID, arg.UserID)
	return err
}

const addAssetToAlbum = `
INSERT INTO album_assets (album_id, asset_id, sort_order)
VALUES ($1::uuid, $2::uuid, $3)
ON CONFLICT (album_id, asset_id)
DO UPDATE SET sort_order = EXCLUDED.sort_order
`

type AddAssetToAlbumParams struct {
	AlbumID   string
	AssetID   string
	SortOrder *int64
}

func (q *Queries) AddAssetToAlbum(ctx context.Context, arg AddAssetToAlbumParams) error {
	_, err := q.db.Exec(ctx, addAssetToAlbum, arg.AlbumID, arg.AssetID, arg.SortOrder)
	return err
}

const removeAssetFromAlbum = `DELETE FROM album_assets WHERE album_id = $1::uuid AND asset_id = $2::uuid`

type RemoveAssetFromAlbumParams struct {
	AlbumID string
	AssetID string
}

func (q *Queries) RemoveAssetFromAlbum(ctx context.Context, arg RemoveAssetFromAlbumParams) error {
	_, err := q.db.Exec(ctx, removeAssetFromAlbum, arg.AlbumID, arg.AssetID)
	return err
}

const listAlbumAssets = `
SELECT a.id::text, a.user_id::text, a.storage_provider, a.bucket, a.object_key, a.thumbnail_key,
  a.preview_key, a.poster_frame_key, a.media_type, a.mime_type, a.original_filename, a.file_size_bytes,
  a.checksum_sha256, a.perceptual_hash, a.taken_at, a.taken_at_source, a.timezone_offset_minutes,
  a.width, a.height, a.orientation, a.duration_ms, a.latitude, a.longitude, a.country, a.region, a.city,
  a.place_name, a.camera_make, a.camera_model, a.software, a.blurhash, a.dominant_color, a.is_favorite,
  a.is_archived, a.is_hidden, a.is_trashed, a.trashed_at, a.uploaded_at, a.created_at, a.updated_at
FROM album_assets aa
JOIN albums al ON al.id = aa.album_id
JOIN assets a ON a.id = aa.asset_id
WHERE aa.album_id = $1::uuid AND al.user_id = $2::uuid
ORDER BY aa.sort_order NULLS LAST, aa.added_at DESC
`

type ListAlbumAssetsParams struct {
	AlbumID string
	UserID  string
}

func (q *Queries) ListAlbumAssets(ctx context.Context, arg ListAlbumAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAlbumAssets, arg.AlbumID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	assets := make([]Asset, 0)
	for rows.Next() {
		asset, err := scanAsset(rows)
		if err != nil {
			return nil, err
		}
		assets = append(assets, asset)
	}
	return assets, rows.Err()
}

type albumScanner interface {
	Scan(dest ...interface{}) error
}

func scanAlbum(row albumScanner) (Album, error) {
	var album Album
	err := row.Scan(
		&album.ID,
		&album.UserID,
		&album.Name,
		&album.Description,
		&album.CoverAssetID,
		&album.IsArchived,
		&album.CreatedAt,
		&album.UpdatedAt,
	)
	return album, err
}
