// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import "context"

const insertAssetChange = `
INSERT INTO asset_changes (user_id, asset_id, change_type, asset_snapshot)
VALUES ($1::uuid, $2::uuid, $3, $4::jsonb)
RETURNING change_id, user_id::text, asset_id::text, change_type,
  asset_snapshot, changed_at
`

type InsertAssetChangeParams struct {
	UserID        string
	AssetID       string
	ChangeType    string
	AssetSnapshot []byte
}

func (q *Queries) InsertAssetChange(ctx context.Context, arg InsertAssetChangeParams) (AssetChange, error) {
	var change AssetChange
	err := q.db.QueryRow(
		ctx,
		insertAssetChange,
		arg.UserID,
		arg.AssetID,
		arg.ChangeType,
		arg.AssetSnapshot,
	).Scan(
		&change.ChangeID,
		&change.UserID,
		&change.AssetID,
		&change.ChangeType,
		&change.AssetSnapshot,
		&change.ChangedAt,
	)
	return change, err
}

const listAssetChangesAfterCursor = `
SELECT change_id, user_id::text, asset_id::text, change_type,
  asset_snapshot, changed_at
FROM asset_changes
WHERE user_id = $1::uuid
  AND change_id > $2
ORDER BY change_id ASC
LIMIT $3
`

type ListAssetChangesAfterCursorParams struct {
	UserID string
	Cursor int64
	Limit  int32
}

func (q *Queries) ListAssetChangesAfterCursor(
	ctx context.Context,
	arg ListAssetChangesAfterCursorParams,
) ([]AssetChange, error) {
	rows, err := q.db.Query(ctx, listAssetChangesAfterCursor, arg.UserID, arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	changes := make([]AssetChange, 0)
	for rows.Next() {
		var change AssetChange
		if err := rows.Scan(
			&change.ChangeID,
			&change.UserID,
			&change.AssetID,
			&change.ChangeType,
			&change.AssetSnapshot,
			&change.ChangedAt,
		); err != nil {
			return nil, err
		}
		changes = append(changes, change)
	}
	return changes, rows.Err()
}

const getLatestAssetChangeIDForUser = `
SELECT COALESCE(MAX(change_id), 0)::bigint
FROM asset_changes
WHERE user_id = $1::uuid
`

func (q *Queries) GetLatestAssetChangeIDForUser(ctx context.Context, userID string) (int64, error) {
	var changeID int64
	err := q.db.QueryRow(ctx, getLatestAssetChangeIDForUser, userID).Scan(&changeID)
	return changeID, err
}

const countAssetsWithoutChanges = `
SELECT COUNT(*)::bigint
FROM assets a
WHERE NOT EXISTS (
  SELECT 1 FROM asset_changes ac WHERE ac.asset_id = a.id
)
`

func (q *Queries) CountAssetsWithoutChanges(ctx context.Context) (int64, error) {
	var count int64
	err := q.db.QueryRow(ctx, countAssetsWithoutChanges).Scan(&count)
	return count, err
}

const listAssetsWithoutChanges = `
SELECT a.id::text, a.user_id::text, a.storage_provider, a.bucket, a.object_key,
  a.thumbnail_key, a.preview_key, a.poster_frame_key, a.media_type, a.mime_type,
  a.original_filename, a.file_size_bytes, a.checksum_sha256, a.perceptual_hash,
  a.taken_at, a.taken_at_source, a.timezone_offset_minutes, a.width, a.height,
  a.orientation, a.duration_ms, a.latitude, a.longitude, a.country, a.region,
  a.city, a.place_name, a.camera_make, a.camera_model, a.software, a.blurhash,
  a.dominant_color, a.is_favorite, a.is_archived, a.is_hidden, a.is_trashed,
  a.trashed_at, a.uploaded_at, a.created_at, a.updated_at
FROM assets a
WHERE NOT EXISTS (
  SELECT 1 FROM asset_changes ac WHERE ac.asset_id = a.id
)
ORDER BY a.user_id, a.id
`

func (q *Queries) ListAssetsWithoutChanges(ctx context.Context) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsWithoutChanges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	assets := make([]Asset, 0)
	for rows.Next() {
		asset, err := scanAsset(rows)
		if err != nil {
			return nil, err
		}
		assets = append(assets, asset)
	}
	return assets, rows.Err()
}

const insertInitialAssetChangeIfMissing = `
INSERT INTO asset_changes (user_id, asset_id, change_type, asset_snapshot)
SELECT a.user_id, a.id, 'upsert', $3::jsonb
FROM assets a
WHERE a.user_id = $1::uuid
  AND a.id = $2::uuid
  AND NOT EXISTS (
  SELECT 1 FROM asset_changes WHERE asset_id = $2::uuid
)
RETURNING change_id
`

type InsertInitialAssetChangeIfMissingParams struct {
	UserID        string
	AssetID       string
	AssetSnapshot []byte
}

func (q *Queries) InsertInitialAssetChangeIfMissing(
	ctx context.Context,
	arg InsertInitialAssetChangeIfMissingParams,
) (int64, error) {
	var changeID int64
	err := q.db.QueryRow(
		ctx,
		insertInitialAssetChangeIfMissing,
		arg.UserID,
		arg.AssetID,
		arg.AssetSnapshot,
	).Scan(&changeID)
	return changeID, err
}

const acquireAssetChangesBackfillLock = `
SELECT true AS locked
FROM (SELECT pg_advisory_xact_lock(hashtext('asset_changes_backfill'))) AS lock
`

func (q *Queries) AcquireAssetChangesBackfillLock(ctx context.Context) (bool, error) {
	var locked bool
	err := q.db.QueryRow(ctx, acquireAssetChangesBackfillLock).Scan(&locked)
	return locked, err
}
