// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import (
	"context"
	"time"
)

const createAsset = `
INSERT INTO assets (
  user_id,
  bucket,
  object_key,
  thumbnail_key,
  preview_key,
  poster_frame_key,
  media_type,
  mime_type,
  original_filename,
  file_size_bytes,
  checksum_sha256,
  taken_at,
  taken_at_source,
  timezone_offset_minutes,
  width,
  height,
  orientation,
  duration_ms,
  latitude,
  longitude,
  camera_make,
  camera_model,
  software
)
VALUES (
  $1::uuid, $2, $3, $4, $5, $6, $7, $8, $9, $10,
  $11, $12, $13, $14, $15, $16, $17, $18, $19, $20,
  $21, $22, $23
)
RETURNING id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
`

type CreateAssetParams struct {
	UserID                string
	Bucket                string
	ObjectKey             string
	ThumbnailKey          *string
	PreviewKey            *string
	PosterFrameKey        *string
	MediaType             string
	MimeType              string
	OriginalFilename      *string
	FileSizeBytes         int64
	ChecksumSha256        string
	TakenAt               *time.Time
	TakenAtSource         *string
	TimezoneOffsetMinutes *int16
	Width                 *int32
	Height                *int32
	Orientation           *int16
	DurationMs            *int64
	Latitude              *float64
	Longitude             *float64
	CameraMake            *string
	CameraModel           *string
	Software              *string
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(
		ctx,
		createAsset,
		arg.UserID,
		arg.Bucket,
		arg.ObjectKey,
		arg.ThumbnailKey,
		arg.PreviewKey,
		arg.PosterFrameKey,
		arg.MediaType,
		arg.MimeType,
		arg.OriginalFilename,
		arg.FileSizeBytes,
		arg.ChecksumSha256,
		arg.TakenAt,
		arg.TakenAtSource,
		arg.TimezoneOffsetMinutes,
		arg.Width,
		arg.Height,
		arg.Orientation,
		arg.DurationMs,
		arg.Latitude,
		arg.Longitude,
		arg.CameraMake,
		arg.CameraModel,
		arg.Software,
	)
	return scanAsset(row)
}

const getAssetByIDForUser = `
SELECT id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
FROM assets
WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetAssetByIDForUserParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetAssetByIDForUser(ctx context.Context, arg GetAssetByIDForUserParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByIDForUser, arg.ID, arg.UserID)
	return scanAsset(row)
}

const listAssetsTimeline = `
SELECT id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
FROM assets
WHERE user_id = $1::uuid AND is_trashed = false
ORDER BY taken_at DESC NULLS LAST, id DESC
LIMIT $2 OFFSET $3
`

type ListAssetsTimelineParams struct {
	UserID string
	Limit  int32
	Offset int32
}

func (q *Queries) ListAssetsTimeline(ctx context.Context, arg ListAssetsTimelineParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsTimeline, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	assets := make([]Asset, 0)
	for rows.Next() {
		asset, err := scanAsset(rows)
		if err != nil {
			return nil, err
		}
		assets = append(assets, asset)
	}
	return assets, rows.Err()
}

const listAssetsFiltered = `
SELECT id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
FROM assets
WHERE user_id = $1::uuid
  AND ($2::text IS NULL OR media_type = $2)
  AND ($3::boolean IS NULL OR is_favorite = $3)
  AND ($4::boolean IS NULL OR is_archived = $4)
  AND is_trashed = $5
  AND ($6::text IS NULL OR city = $6)
  AND ($7::timestamptz IS NULL OR taken_at >= $7)
  AND ($8::timestamptz IS NULL OR taken_at <= $8)
  AND (
    $9::uuid IS NULL
    OR (
      $10::timestamptz IS NOT NULL
      AND (taken_at < $10 OR (taken_at = $10 AND id < $9::uuid) OR taken_at IS NULL)
    )
    OR (
      $10::timestamptz IS NULL
      AND taken_at IS NULL
      AND id < $9::uuid
    )
  )
ORDER BY taken_at DESC NULLS LAST, id DESC
LIMIT $11
`

type ListAssetsFilteredParams struct {
	UserID        string
	MediaType     *string
	Favorite      *bool
	Archived      *bool
	Trashed       bool
	City          *string
	From          *time.Time
	To            *time.Time
	CursorID      *string
	CursorTakenAt *time.Time
	Limit         int32
}

func (q *Queries) ListAssetsFiltered(ctx context.Context, arg ListAssetsFilteredParams) ([]Asset, error) {
	rows, err := q.db.Query(
		ctx,
		listAssetsFiltered,
		arg.UserID,
		arg.MediaType,
		arg.Favorite,
		arg.Archived,
		arg.Trashed,
		arg.City,
		arg.From,
		arg.To,
		arg.CursorID,
		arg.CursorTakenAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	assets := make([]Asset, 0)
	for rows.Next() {
		asset, err := scanAsset(rows)
		if err != nil {
			return nil, err
		}
		assets = append(assets, asset)
	}
	return assets, rows.Err()
}

const updateAssetFavorite = `
UPDATE assets SET is_favorite = $3
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
`

type UpdateAssetFavoriteParams struct {
	ID         string
	UserID     string
	IsFavorite bool
}

func (q *Queries) UpdateAssetFavorite(ctx context.Context, arg UpdateAssetFavoriteParams) (Asset, error) {
	return scanAsset(q.db.QueryRow(ctx, updateAssetFavorite, arg.ID, arg.UserID, arg.IsFavorite))
}

const updateAssetArchive = `
UPDATE assets SET is_archived = $3
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
`

type UpdateAssetArchiveParams struct {
	ID         string
	UserID     string
	IsArchived bool
}

func (q *Queries) UpdateAssetArchive(ctx context.Context, arg UpdateAssetArchiveParams) (Asset, error) {
	return scanAsset(q.db.QueryRow(ctx, updateAssetArchive, arg.ID, arg.UserID, arg.IsArchived))
}

const moveAssetToTrash = `
UPDATE assets SET is_trashed = true, trashed_at = now()
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
`

func (q *Queries) MoveAssetToTrash(ctx context.Context, arg GetAssetByIDForUserParams) (Asset, error) {
	return scanAsset(q.db.QueryRow(ctx, moveAssetToTrash, arg.ID, arg.UserID))
}

const restoreAssetFromTrash = `
UPDATE assets SET is_trashed = false, trashed_at = NULL
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text, user_id::text, storage_provider, bucket, object_key, thumbnail_key,
  preview_key, poster_frame_key, media_type, mime_type, original_filename, file_size_bytes,
  checksum_sha256, perceptual_hash, taken_at, taken_at_source, timezone_offset_minutes,
  width, height, orientation, duration_ms, latitude, longitude, country, region, city,
  place_name, camera_make, camera_model, software, blurhash, dominant_color, is_favorite,
  is_archived, is_hidden, is_trashed, trashed_at, uploaded_at, created_at, updated_at
`

func (q *Queries) RestoreAssetFromTrash(ctx context.Context, arg GetAssetByIDForUserParams) (Asset, error) {
	return scanAsset(q.db.QueryRow(ctx, restoreAssetFromTrash, arg.ID, arg.UserID))
}

const deleteAssetByID = `DELETE FROM assets WHERE id = $1::uuid AND user_id = $2::uuid`

func (q *Queries) DeleteAssetByID(ctx context.Context, arg GetAssetByIDForUserParams) error {
	_, err := q.db.Exec(ctx, deleteAssetByID, arg.ID, arg.UserID)
	return err
}

const createOrUpdateDeviceAsset = `
INSERT INTO device_assets (
  user_id, device_id, asset_id, local_asset_id, local_uri, local_created_at,
  local_modified_at, sync_status, last_error, last_synced_at
)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (user_id, device_id, local_asset_id)
DO UPDATE SET
  asset_id = EXCLUDED.asset_id,
  local_uri = EXCLUDED.local_uri,
  local_created_at = EXCLUDED.local_created_at,
  local_modified_at = EXCLUDED.local_modified_at,
  sync_status = EXCLUDED.sync_status,
  last_error = EXCLUDED.last_error,
  last_synced_at = EXCLUDED.last_synced_at
`

type CreateOrUpdateDeviceAssetParams struct {
	UserID          string
	DeviceID        string
	AssetID         *string
	LocalAssetID    string
	LocalURI        *string
	LocalCreatedAt  *time.Time
	LocalModifiedAt *time.Time
	SyncStatus      string
	LastError       *string
	LastSyncedAt    *time.Time
}

func (q *Queries) CreateOrUpdateDeviceAsset(ctx context.Context, arg CreateOrUpdateDeviceAssetParams) error {
	_, err := q.db.Exec(ctx, createOrUpdateDeviceAsset, arg.UserID, arg.DeviceID, arg.AssetID, arg.LocalAssetID, arg.LocalURI, arg.LocalCreatedAt, arg.LocalModifiedAt, arg.SyncStatus, arg.LastError, arg.LastSyncedAt)
	return err
}

type assetScanner interface {
	Scan(dest ...interface{}) error
}

func scanAsset(row assetScanner) (Asset, error) {
	var asset Asset
	err := row.Scan(
		&asset.ID,
		&asset.UserID,
		&asset.StorageProvider,
		&asset.Bucket,
		&asset.ObjectKey,
		&asset.ThumbnailKey,
		&asset.PreviewKey,
		&asset.PosterFrameKey,
		&asset.MediaType,
		&asset.MimeType,
		&asset.OriginalFilename,
		&asset.FileSizeBytes,
		&asset.ChecksumSha256,
		&asset.PerceptualHash,
		&asset.TakenAt,
		&asset.TakenAtSource,
		&asset.TimezoneOffsetMinutes,
		&asset.Width,
		&asset.Height,
		&asset.Orientation,
		&asset.DurationMs,
		&asset.Latitude,
		&asset.Longitude,
		&asset.Country,
		&asset.Region,
		&asset.City,
		&asset.PlaceName,
		&asset.CameraMake,
		&asset.CameraModel,
		&asset.Software,
		&asset.Blurhash,
		&asset.DominantColor,
		&asset.IsFavorite,
		&asset.IsArchived,
		&asset.IsHidden,
		&asset.IsTrashed,
		&asset.TrashedAt,
		&asset.UploadedAt,
		&asset.CreatedAt,
		&asset.UpdatedAt,
	)
	return asset, err
}

const searchAssets = `
SELECT a.id::text, a.user_id::text, a.storage_provider, a.bucket, a.object_key, a.thumbnail_key,
  a.preview_key, a.poster_frame_key, a.media_type, a.mime_type, a.original_filename, a.file_size_bytes,
  a.checksum_sha256, a.perceptual_hash, a.taken_at, a.taken_at_source, a.timezone_offset_minutes,
  a.width, a.height, a.orientation, a.duration_ms, a.latitude, a.longitude, a.country, a.region, a.city,
  a.place_name, a.camera_make, a.camera_model, a.software, a.blurhash, a.dominant_color, a.is_favorite,
  a.is_archived, a.is_hidden, a.is_trashed, a.trashed_at, a.uploaded_at, a.created_at, a.updated_at
FROM assets a
JOIN asset_search_metadata asm ON asm.asset_id = a.id
WHERE a.user_id = $1::uuid
  AND a.is_trashed = false
  AND asm.search_vector @@ plainto_tsquery('english', $2)
ORDER BY ts_rank(asm.search_vector, plainto_tsquery('english', $2)) DESC, a.taken_at DESC NULLS LAST
LIMIT $3 OFFSET $4
`

type SearchAssetsParams struct {
	UserID string
	Query  string
	Limit  int32
	Offset int32
}

func (q *Queries) SearchAssets(ctx context.Context, arg SearchAssetsParams) ([]Asset, error) {
	rows, err := q.db.Query(ctx, searchAssets, arg.UserID, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	assets := make([]Asset, 0)
	for rows.Next() {
		asset, err := scanAsset(rows)
		if err != nil {
			return nil, err
		}
		assets = append(assets, asset)
	}
	return assets, rows.Err()
}
