// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import "context"

const upsertDevice = `
INSERT INTO devices (user_id, device_name, platform, device_fingerprint, last_seen_at)
VALUES ($1::uuid, $2, $3, $4, now())
ON CONFLICT (user_id, device_fingerprint)
DO UPDATE SET
  device_name = EXCLUDED.device_name,
  platform = EXCLUDED.platform,
  last_seen_at = now(),
  updated_at = now()
RETURNING id::text, user_id::text, coalesce(device_name, ''), platform, device_fingerprint, last_seen_at, created_at, updated_at
`

type UpsertDeviceParams struct {
	UserID            string
	DeviceName        string
	Platform          string
	DeviceFingerprint string
}

func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, upsertDevice, arg.UserID, arg.DeviceName, arg.Platform, arg.DeviceFingerprint)
	var device Device
	err := row.Scan(
		&device.ID,
		&device.UserID,
		&device.DeviceName,
		&device.Platform,
		&device.DeviceFingerprint,
		&device.LastSeenAt,
		&device.CreatedAt,
		&device.UpdatedAt,
	)
	return device, err
}

const listDevicesByUserID = `
SELECT id::text, user_id::text, coalesce(device_name, ''), platform, device_fingerprint, last_seen_at, created_at, updated_at
FROM devices
WHERE user_id = $1::uuid
ORDER BY last_seen_at DESC
`

func (q *Queries) ListDevicesByUserID(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevicesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	devices := make([]Device, 0)
	for rows.Next() {
		var device Device
		if err := rows.Scan(
			&device.ID,
			&device.UserID,
			&device.DeviceName,
			&device.Platform,
			&device.DeviceFingerprint,
			&device.LastSeenAt,
			&device.CreatedAt,
			&device.UpdatedAt,
		); err != nil {
			return nil, err
		}
		devices = append(devices, device)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return devices, nil
}

const getDeviceByIDAndUserID = `
SELECT id::text, user_id::text, coalesce(device_name, ''), platform, device_fingerprint, last_seen_at, created_at, updated_at
FROM devices
WHERE id = $1::uuid AND user_id = $2::uuid
`

type GetDeviceByIDAndUserIDParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetDeviceByIDAndUserID(ctx context.Context, arg GetDeviceByIDAndUserIDParams) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByIDAndUserID, arg.ID, arg.UserID)
	var device Device
	err := row.Scan(
		&device.ID,
		&device.UserID,
		&device.DeviceName,
		&device.Platform,
		&device.DeviceFingerprint,
		&device.LastSeenAt,
		&device.CreatedAt,
		&device.UpdatedAt,
	)
	return device, err
}
