// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import (
	"context"
	"time"
)

const listExpiredIncompleteUploadSessions = `
SELECT id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
FROM upload_sessions
WHERE status IN ('created', 'uploading', 'uploaded', 'failed', 'expired')
  AND asset_id IS NULL
  AND expires_at < $1
ORDER BY expires_at ASC
LIMIT $2
`

type ListExpiredIncompleteUploadSessionsParams struct {
	ExpiresBefore time.Time
	Limit         int32
}

func (q *Queries) ListExpiredIncompleteUploadSessions(ctx context.Context, arg ListExpiredIncompleteUploadSessionsParams) ([]UploadSession, error) {
	rows, err := q.db.Query(ctx, listExpiredIncompleteUploadSessions, arg.ExpiresBefore, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	sessions := make([]UploadSession, 0)
	for rows.Next() {
		session, err := scanUploadSession(rows)
		if err != nil {
			return nil, err
		}
		sessions = append(sessions, session)
	}
	return sessions, rows.Err()
}

const markUploadSessionExpired = `
UPDATE upload_sessions
SET status = 'expired', error_message = $3
WHERE id = $1::uuid
  AND user_id = $2::uuid
  AND asset_id IS NULL
  AND status IN ('created', 'uploading', 'uploaded', 'failed', 'expired')
RETURNING id::text
`

type MarkUploadSessionExpiredParams struct {
	ID           string
	UserID       string
	ErrorMessage *string
}

func (q *Queries) MarkUploadSessionExpired(ctx context.Context, arg MarkUploadSessionExpiredParams) (string, error) {
	var id string
	err := q.db.QueryRow(ctx, markUploadSessionExpired, arg.ID, arg.UserID, arg.ErrorMessage).Scan(&id)
	return id, err
}

const checkObjectKeyUsedByAsset = `
SELECT EXISTS (
  SELECT 1
  FROM assets
  WHERE object_key = $1
    OR thumbnail_key = $1
    OR preview_key = $1
    OR poster_frame_key = $1
)
`

func (q *Queries) CheckObjectKeyUsedByAsset(ctx context.Context, objectKey string) (bool, error) {
	var used bool
	err := q.db.QueryRow(ctx, checkObjectKeyUsedByAsset, objectKey).Scan(&used)
	return used, err
}

const createAuditLog = `
INSERT INTO audit_logs (user_id, action, entity_type, entity_id, metadata)
VALUES ($1::uuid, $2, $3, $4::uuid, $5::jsonb)
`

type CreateAuditLogParams struct {
	UserID     *string
	Action     string
	EntityType *string
	EntityID   *string
	Metadata   string
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error {
	_, err := q.db.Exec(ctx, createAuditLog, arg.UserID, arg.Action, arg.EntityType, arg.EntityID, arg.Metadata)
	return err
}
