// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import (
	"context"
	"time"
)

const createUploadSession = `
INSERT INTO upload_sessions (
  user_id,
  device_id,
  local_asset_id,
  object_key,
  thumbnail_key,
  preview_key,
  poster_frame_key,
  bucket,
  media_type,
  mime_type,
  original_filename,
  file_size_bytes,
  expected_checksum_sha256,
  status,
  expires_at
)
VALUES ($1::uuid, $2::uuid, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 'created', $14)
RETURNING id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
`

type CreateUploadSessionParams struct {
	UserID                 string
	DeviceID               string
	LocalAssetID           string
	ObjectKey              string
	ThumbnailKey           string
	PreviewKey             string
	PosterFrameKey         *string
	Bucket                 string
	MediaType              string
	MimeType               string
	OriginalFilename       string
	FileSizeBytes          int64
	ExpectedChecksumSha256 *string
	ExpiresAt              time.Time
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(
		ctx,
		createUploadSession,
		arg.UserID,
		arg.DeviceID,
		arg.LocalAssetID,
		arg.ObjectKey,
		arg.ThumbnailKey,
		arg.PreviewKey,
		arg.PosterFrameKey,
		arg.Bucket,
		arg.MediaType,
		arg.MimeType,
		arg.OriginalFilename,
		arg.FileSizeBytes,
		arg.ExpectedChecksumSha256,
		arg.ExpiresAt,
	)
	return scanUploadSession(row)
}

const getUploadSessionForUpdate = `
SELECT id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
FROM upload_sessions
WHERE id = $1::uuid
FOR UPDATE
`

func (q *Queries) GetUploadSessionForUpdate(ctx context.Context, id string) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionForUpdate, id)
	return scanUploadSession(row)
}

const completeUploadSession = `
UPDATE upload_sessions
SET status = 'completed', asset_id = $2::uuid, completed_at = now()
WHERE id = $1::uuid
RETURNING id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
`

type CompleteUploadSessionParams struct {
	ID      string
	AssetID string
}

func (q *Queries) CompleteUploadSession(ctx context.Context, arg CompleteUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, completeUploadSession, arg.ID, arg.AssetID)
	return scanUploadSession(row)
}

type uploadSessionScanner interface {
	Scan(dest ...interface{}) error
}

func scanUploadSession(row uploadSessionScanner) (UploadSession, error) {
	var session UploadSession
	err := row.Scan(
		&session.ID,
		&session.UserID,
		&session.DeviceID,
		&session.LocalAssetID,
		&session.ObjectKey,
		&session.ThumbnailKey,
		&session.PreviewKey,
		&session.PosterFrameKey,
		&session.Bucket,
		&session.MediaType,
		&session.MimeType,
		&session.OriginalFilename,
		&session.FileSizeBytes,
		&session.ExpectedChecksumSha256,
		&session.Status,
		&session.AssetID,
		&session.ErrorMessage,
		&session.ExpiresAt,
		&session.CompletedAt,
		&session.CreatedAt,
		&session.UpdatedAt,
	)
	return session, err
}
