// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import (
	"context"
	"time"
)

const createUploadSession = `
INSERT INTO upload_sessions (
  user_id,
  device_id,
  local_asset_id,
  object_key,
  thumbnail_key,
  preview_key,
  poster_frame_key,
  bucket,
  media_type,
  mime_type,
  original_filename,
  file_size_bytes,
  expected_checksum_sha256,
  status,
  expires_at
)
VALUES ($1::uuid, $2::uuid, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, 'created', $14)
RETURNING id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
`

type CreateUploadSessionParams struct {
	UserID                 string
	DeviceID               string
	LocalAssetID           string
	ObjectKey              string
	ThumbnailKey           string
	PreviewKey             string
	PosterFrameKey         *string
	Bucket                 string
	MediaType              string
	MimeType               string
	OriginalFilename       string
	FileSizeBytes          int64
	ExpectedChecksumSha256 *string
	ExpiresAt              time.Time
}

func (q *Queries) CreateUploadSession(ctx context.Context, arg CreateUploadSessionParams) (UploadSession, error) {
	row := q.db.QueryRow(
		ctx,
		createUploadSession,
		arg.UserID,
		arg.DeviceID,
		arg.LocalAssetID,
		arg.ObjectKey,
		arg.ThumbnailKey,
		arg.PreviewKey,
		arg.PosterFrameKey,
		arg.Bucket,
		arg.MediaType,
		arg.MimeType,
		arg.OriginalFilename,
		arg.FileSizeBytes,
		arg.ExpectedChecksumSha256,
		arg.ExpiresAt,
	)
	return scanUploadSession(row)
}

const getActiveUploadSessionByLocalAsset = `
SELECT id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
FROM upload_sessions
WHERE user_id = $1::uuid
  AND device_id = $2::uuid
  AND local_asset_id = $3
  AND status IN ('created', 'uploading', 'uploaded', 'processing')
  AND expires_at > now()
ORDER BY expires_at DESC
LIMIT 1
`

type GetActiveUploadSessionByLocalAssetParams struct {
	UserID       string
	DeviceID     string
	LocalAssetID string
}

func (q *Queries) GetActiveUploadSessionByLocalAsset(ctx context.Context, arg GetActiveUploadSessionByLocalAssetParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getActiveUploadSessionByLocalAsset, arg.UserID, arg.DeviceID, arg.LocalAssetID)
	return scanUploadSession(row)
}

const getUploadSessionForUpdate = `
SELECT id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
FROM upload_sessions
WHERE id = $1::uuid AND user_id = $2::uuid
FOR UPDATE
`

type GetUploadSessionForUpdateParams struct {
	ID     string
	UserID string
}

func (q *Queries) GetUploadSessionForUpdate(ctx context.Context, arg GetUploadSessionForUpdateParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, getUploadSessionForUpdate, arg.ID, arg.UserID)
	return scanUploadSession(row)
}

const resumeUploadSession = `
UPDATE upload_sessions
SET expires_at = $3,
  status = CASE WHEN status IN ('failed', 'expired') THEN 'created' ELSE status END,
  error_message = NULL
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
`

type ResumeUploadSessionParams struct {
	ID        string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) ResumeUploadSession(ctx context.Context, arg ResumeUploadSessionParams) (UploadSession, error) {
	return scanUploadSession(q.db.QueryRow(ctx, resumeUploadSession, arg.ID, arg.UserID, arg.ExpiresAt))
}

const updateUploadSessionStatus = `
UPDATE upload_sessions
SET status = $3, error_message = $4
WHERE id = $1::uuid AND user_id = $2::uuid
RETURNING id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
`

type UpdateUploadSessionStatusParams struct {
	ID           string
	UserID       string
	Status       string
	ErrorMessage *string
}

func (q *Queries) UpdateUploadSessionStatus(ctx context.Context, arg UpdateUploadSessionStatusParams) (UploadSession, error) {
	return scanUploadSession(q.db.QueryRow(
		ctx,
		updateUploadSessionStatus,
		arg.ID,
		arg.UserID,
		arg.Status,
		arg.ErrorMessage,
	))
}

const markUploadSessionCompleted = `
UPDATE upload_sessions
SET status = 'completed', asset_id = $2::uuid, completed_at = now()
WHERE id = $1::uuid AND user_id = $3::uuid
RETURNING id::text, user_id::text, device_id::text, local_asset_id, object_key, thumbnail_key,
  preview_key, poster_frame_key, bucket, media_type, mime_type, original_filename,
  file_size_bytes, expected_checksum_sha256, status, asset_id::text, error_message, expires_at,
  completed_at, created_at, updated_at
`

type MarkUploadSessionCompletedParams struct {
	ID      string
	AssetID string
	UserID  string
}

func (q *Queries) MarkUploadSessionCompleted(ctx context.Context, arg MarkUploadSessionCompletedParams) (UploadSession, error) {
	row := q.db.QueryRow(ctx, markUploadSessionCompleted, arg.ID, arg.AssetID, arg.UserID)
	return scanUploadSession(row)
}

type uploadSessionScanner interface {
	Scan(dest ...interface{}) error
}

func scanUploadSession(row uploadSessionScanner) (UploadSession, error) {
	var session UploadSession
	err := row.Scan(
		&session.ID,
		&session.UserID,
		&session.DeviceID,
		&session.LocalAssetID,
		&session.ObjectKey,
		&session.ThumbnailKey,
		&session.PreviewKey,
		&session.PosterFrameKey,
		&session.Bucket,
		&session.MediaType,
		&session.MimeType,
		&session.OriginalFilename,
		&session.FileSizeBytes,
		&session.ExpectedChecksumSha256,
		&session.Status,
		&session.AssetID,
		&session.ErrorMessage,
		&session.ExpiresAt,
		&session.CompletedAt,
		&session.CreatedAt,
		&session.UpdatedAt,
	)
	return session, err
}
