// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc placeholder for initial MVP scaffold

package sqlc

import "context"

const createUser = `
INSERT INTO app_users (email, display_name, password_hash)
VALUES ($1, $2, $3)
RETURNING id::text, email, coalesce(display_name, ''), password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	DisplayName  string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.DisplayName, arg.PasswordHash)
	var user User
	err := row.Scan(
		&user.ID,
		&user.Email,
		&user.DisplayName,
		&user.PasswordHash,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	return user, err
}

const getUserByEmail = `
SELECT id::text, email, coalesce(display_name, ''), password_hash, created_at, updated_at
FROM app_users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var user User
	err := row.Scan(
		&user.ID,
		&user.Email,
		&user.DisplayName,
		&user.PasswordHash,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	return user, err
}

const getUserByID = `
SELECT id::text, email, coalesce(display_name, ''), password_hash, created_at, updated_at
FROM app_users
WHERE id = $1::uuid
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var user User
	err := row.Scan(
		&user.ID,
		&user.Email,
		&user.DisplayName,
		&user.PasswordHash,
		&user.CreatedAt,
		&user.UpdatedAt,
	)
	return user, err
}
